name: Sync Scripts to Scripts-Only Repo

permissions:
  contents: write

on:
  push:
    branches:
      - main  # or master, depending on your default branch
    paths:
      - 'scripts/**'  # Only trigger when files in the scripts directory change

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Files
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          CONFIG_PATH: .github/sync.yml
          SKIP_PR: true
